export const Data1 = [
  { id: "1", img: "planta1.jpg" },
  { id: "2", img: "planta2.jpg" },
  { id: "3", img: "planta3.jpg" },
  { id: "4", img: "planta4.jpg" },
  { id: "5", img: "planta5.jpg" },
  { id: "6", img: "planta6.jpg" },
  { id: "7", img: "planta7.jpg" },
  { id: "8", img: "planta8.jpg" },
  { id: "9", img: "planta9.jpg" },
  { id: "10", img: "planta10.jpg" },
  { id: "11", img: "planta11.jpg" },
  { id: "12", img: "planta12.jpg" },
  { id: "13", img: "planta13.jpg" },
  { id: "14", img: "planta14.jpg" },
  { id: "15", img: "planta15.jpg" },
  { id: "16", img: "planta16.jpg" },
  { id: "17", img: "planta17.jpg" },
  { id: "18", img: "planta18.jpg" },
  { id: "19", img: "planta19.jpg" },
  { id: "20", img: "planta20.jpg" } 
  ];
  
  export const Data2 = [
    { id: "1", img: "animal1.jpg" },
    { id: "2", img: "animal2.jpg" },
    { id: "3", img: "animal3.jpg" },
    { id: "4", img: "animal4.jpg" },
    { id: "5", img: "animal5.jpg" },
    { id: "6", img: "animal6.jpg" },
    { id: "7", img: "animal7.jpg" },
    { id: "8", img: "animal8.jpg" },
    { id: "9", img: "animal9.jpg" },
    { id: "10", img: "animal10.jpg" },
    { id: "11", img: "animal11.jpg" },
    { id: "12", img: "animal12.jpg" },
    { id: "13", img: "animal13.jpg" },
    { id: "14", img: "animal14.jpg" },
    { id: "15", img: "animal15.jpg" },
    { id: "16", img: "animal16.jpg" },
    { id: "17", img: "animal17.jpg" },
    { id: "18", img: "animal18.jpg" },
    { id: "19", img: "animal19.jpg" },
    { id: "20", img: "animal20.jpg" }
  ];
  
  export const Data3 = [
      { id: "1", img: "estructura.jpg" },
      { id: "2", img: "estructura2.jpg" },
      { id: "3", img: "estructura3.jpg" },
      { id: "4", img: "estructura4.jpg" },
      { id: "5", img: "estructura5.jpg" },
      { id: "6", img: "estructura6.jpg" },
      { id: "7", img: "estructura7.jpg" },
      { id: "8", img: "estructura8.jpg" },
      { id: "9", img: "estructura9.jpg" },
      { id: "10", img: "estructura10.jpg" },
      { id: "11", img: "estructura11.jpg" },
      { id: "12", img: "estructura12.jpg" },
      { id: "13", img: "estructura13.jpg" },
      { id: "14", img: "estructura14.jpg" },
      { id: "15", img: "estructura15.jpg" },
      { id: "16", img: "estructura16.jpg" },
      { id: "17", img: "estructura17.jpg" },
      { id: "18", img: "estructura18.jpg" },
      { id: "19", img: "estructura19.jpg" },
      { id: "20", img: "estructura20.jpg" }
 ];
 


  export const Data4 = [
    { id: "1", img: "paisaje1.jpg" },
    { id: "2", img: "paisaje2.jpg" },
    { id: "3", img: "paisaje3.jpg" },
    { id: "4", img: "paisaje4.jpg" },
    { id: "5", img: "paisaje5.jpg" },
    { id: "6", img: "paisaje6.jpg" },
    { id: "7", img: "paisaje7.jpg" },
    { id: "8", img: "paisaje8.jpg" },
    { id: "9", img: "paisaje9.jpg" },
    { id: "10", img: "paisaje10.jpg" },
    { id: "11", img: "paisaje11.jpg" },
    { id: "12", img: "paisaje12.jpg" },
    { id: "13", img: "paisaje13.jpg" },
    { id: "14", img: "paisaje14.jpg" },
    { id: "15", img: "paisaje15.jpg" },
    { id: "16", img: "paisaje16.jpg" },
    { id: "17", img: "paisaje17.jpg" },
    { id: "18", img: "paisaje18.jpg" },
    { id: "19", img: "paisaje19.jpg" },
    { id: "20", img: "paisaje20.jpg" },
    { id: "21", img: "paisaje21.jpg" }
  ];
  
  export const Data5 = [
    { id: "1", img: "retrato1.jpg" },
    { id: "2", img: "retrato2.jpg" },
    { id: "3", img: "retrato3.jpg" },
    { id: "4", img: "retrato4.jpg" },
    { id: "5", img: "retrato5.jpg" },
    { id: "6", img: "retrato6.jpg" },
    { id: "7", img: "retrato7.jpg" },
    { id: "8", img: "retrato8.jpg" },
    { id: "9", img: "retrato9.jpg" },
    { id: "10", img: "retrato10.jpg" },
    { id: "11", img: "retrato11.jpg" },
    { id: "12", img: "retrato12.jpg" },
    { id: "13", img: "retrato13.jpg" },
    { id: "14", img: "retrato14.jpg" },
    { id: "15", img: "retrato15.jpg" },
    { id: "16", img: "retrato16.jpg" },
    { id: "17", img: "retrato17.jpg" },
    { id: "18", img: "retrato18.jpg" },
    { id: "19", img: "retrato19.jpg" },
    { id: "20", img: "retrato20.jpg" },
  ];