import React from 'react'
import "../styles/Premium.css";
import Premium13 from "../img/Premium13.jpg";
import Paola1 from "../img/Paola1.jpg";
import Paola2 from "../img/Paola2.jpg";
import Paola3 from "../img/Paola3.jpg";
import Paola4 from "../img/Paola4.jpg";
import Paola5 from "../img/Paola5.jpg";

const EntrevistasPre13 = () => {
  return (
    <div>
       <h1 className='h1-entrevistas'>FOTOGRAFA PAOLA MARÍA SÁNCHEZ </h1>
       <h2 className='subtitulo-entrevistas'>Descubre la Exposición Fotográfica ‘Una Familia Muy Evolutiva’: Una Oda a la Vida Silvestre</h2>
         <div className='Contenedor-texto-entrevistas'>
         </div>
         <div className='imagen-completa-entrevista-ENTREVISTAGENERAL'>
         <div className='imagen-completa-entrevista'>
            <img src={Premium13}  className="img-entrevistas" alt="Imgen no disponible"/>
            </div>   
         </div> 
         <h2 className='subtitulo-entrevistas'>Una Mirada Íntima a la Fauna Silvestre </h2>
         <p className='p-entrevistas'> En el mundo de la fotografía de naturaleza, donde la belleza se entrelaza con la conciencia ambiental, emerge una talentosa fotógrafa cuyo trabajo ha cautivado tanto a expertos como a amantes de la vida salvaje. Paola María Sánchez Gómez, una estudiante destacada de nuestra escuela de fotografía, SieteFotógrafos, se prepara para abrir las puertas de su más reciente exposición: «Una Familia Muy Evolutiva». Esta exhibición, que abrirá sus puertas el próximo 15 de febrero en la universidad EAN, promete ser una oda a la vida silvestre, capturada a través del ojo experto de una fotógrafa apasionada y comprometida. </p>
         <p className='p-entrevistas'> Durante su tiempo en SieteFotógrafos, Paola demostró una dedicación excepcional y una habilidad innata para capturar la esencia de la naturaleza en su forma más pura. Su compromiso con el arte de la fotografía y su incansable búsqueda de la belleza en los rincones más remotos de Colombia la han llevado a convertirse en una de las fotógrafas emergentes más destacadas de nuestra comunidad. Ahora, con su exposición «Una Familia Muy Evolutiva», Paola nos invita a un viaje único a través de la vida salvaje, donde cada imagen es un testimonio de la magia y la fragilidad de nuestro planeta.</p>
         <img src={Paola1}  className="imagen-completa-entrevista" alt="Imgen no disponible"/>
         <h2 className='h2-entrevistas'>Paola, es realmente un gusto conversar nuevamente contigo. Para quienes aun no te conocen, cuéntanos por favor un poco sobre ti y tu trayectoria en el mundo de la fotografía. ¿Qué te inspiró a especializarte en la fotografía de fauna silvestre?</h2>
         <p className='p-entrevistas'>  Mi pasión por la fotografía de vida silvestre surgió como respuesta a mi profundo amor y respeto por la naturaleza. Desde mis primeros años como bióloga, me cautivó la idea de capturar la esencia misma de los seres que habitan nuestro planeta. Inspirada por maestros como Frans Lanting de National Geographic, me embarqué en un viaje fotográfico que me llevó a explorar y documentar la diversidad de la vida salvaje en su entorno natural. Para mí, la fotografía de fauna silvestre no es solo una profesión, es una vocación que me permite conectar con la belleza y la fragilidad de nuestro mundo natural. </p>
         <h2 className='h2-entrevistas'>  ¿Qué nos puedes contar sobre tu exposición fotográfica «Una Familia Muy Evolutiva»?</h2>
         <p className='p-entrevistas'> Científicamente el reino animal tiene una clasificación taxonómica y uno de estas jerarquías es la de familia y en ella se incluyen los géneros y especies más relacionados, algo así como nuestras familias humanas; aunque todos somos humanos, los Sánchez somos bien distintos de los Sanz Jajajajaja., Humanos y animales nos diferenciamos por la evolución pero somos y necesitamos lo mismo, el mismo planeta para todos.  «Una Familia Muy Evolutiva» es más que una simple exhibición de imágenes; es un llamado a la reflexión sobre nuestra relación con el reino animal y nuestro papel como guardianes de este planeta. A través de una cuidadosa selección de fotografías, la exposición explora la diversidad de la vida silvestre y nos invita a contemplar la belleza y la complejidad de los lazos familiares en el mundo animal. Desde los majestuosos felinos hasta las diminutas criaturas que habitan en los rincones más remotos de la Tierra, cada imagen nos recuerda nuestra responsabilidad compartida de proteger y preservar la biodiversidad de nuestro hogar planetario.</p>
         <img src={Paola2}  className="imagen-completa-entrevista" alt="Imgen no disponible"/>
         <h2 className='h2-entrevistas'> ¿Cuál es el mensaje o la historia que esperas transmitir a través de estas fotografías?</h2>
         <p className='p-entrevistas'> A través de «Una Familia Muy Evolutiva», busco inspirar un mayor aprecio y respeto por la vida silvestre y fomentar una mayor conciencia sobre la importancia de conservar nuestros ecosistemas naturales. Cada fotografía es una ventana a un mundo fascinante y diverso, y cada historia capturada en estas imágenes nos recuerda la belleza y la fragilidad de nuestro entorno natural. Más allá de ser una simple exposición, «Una Familia Muy Evolutiva» es un recordatorio de que todos compartimos este planeta y que debemos trabajar juntos para protegerlo para las generaciones futuras. </p>
         <h2 className='h2-entrevistas'> ¿Cómo fue el proceso de capturar estas imágenes de fauna silvestre? ¿Tuviste algún desafío particular durante el proceso creativo?</h2>
         <p className='p-entrevistas'>Durante casi dos décadas, he tenido el privilegio de explorar y documentar la maravillosa diversidad de la vida salvaje. Desde el inicio de mi carrera como bióloga, me sumergí en una apasionante búsqueda por capturar la esencia de cada ser vivo que cruzaba mi camino. Desde las profundidades del océano hasta los rincones más remotos de los ecosistemas terrestres, he dedicado mi vida a inmortalizar la belleza y la majestuosidad de la naturaleza a través de mi lente. </p>
         <img src={Paola3}  className="imagen-completa-entrevista" alt="Imgen no disponible"/>
         <h2 className='h2-entrevistas'> ¿De qué manera SieteFotógrafos influyó en tu desarrollo como fotógrafa? ¿Hay algún momento o lección destacada de tu tiempo en la escuela que te haya sido especialmente útil en este proyecto?</h2>
         <p className='p-entrevistas'> SieteFotógrafos ha sido un faro en mi camino hacia el perfeccionamiento fotográfico. La escuela no solo me impulsó a buscar una formación más sólida, sino que también me animó a explorar nuevos horizontes en el mundo de la fotografía, horizontes que inicialmente ni siquiera había considerado. Aunque mis comienzos fueron autodidactas, SieteFotógrafos me brindó las herramientas y el conocimiento necesario para elevar mi arte a nuevas alturas.Durante mi tiempo en la escuela, establecí sólidas bases técnicas y tuve la oportunidad de participar en diversos cursos como monitora, una experiencia que atesoro con gran orgullo. Estos cursos no solo fortalecieron mi habilidad para capturar la esencia de la vida silvestre, sino que también me permitieron compartir mi pasión y conocimientos con otros entusiastas de la fotografía. </p>
         <h2 className='h2-entrevistas'> ¿Qué esperas lograr con esta exposición fotográfica? ¿Cómo te sientes al ser reconocida como egresada destacada de SieteFotógrafos? </h2>
         <p className='p-entrevistas'> Mi principal objetivo es generar conciencia y sensibilizar a las personas sobre la importancia de cuidar nuestro planeta y todas las formas de vida que lo habitan. Quiero impactar profundamente en los corazones y mentes de las personas, recordándoles que este mundo no es exclusivamente nuestro, los humanos, sino que compartimos esta tierra con innumerables seres vivos que merecen nuestro respeto y protección. Por otro lado, quiero resaltar la importancia de la comunidad que encontré en SieteFotógrafos. Allí, experimenté un sentido de pertenencia y camaradería que me hizo sentir como en familia. Reconocí el valor de tener un sólido sistema de apoyo compuesto por mis compañeros y los maestros que ahora considero amigos cercanos. Sin duda, el respaldo de esta comunidad ha sido fundamental en mi desarrollo como fotógrafa y conservacionista. </p>
         <img src={Paola4}  className="imagen-completa-entrevista" alt="Imgen no disponible"/>
         <h2 className='h2-entrevistas'> ¿Tienes planes para futuros proyectos fotográficos? ¿Puedes adelantarnos algo sobre ellos? ¿Hay alguna otra área de la fotografía que te gustaría explorar en el futuro?</h2>
         <p className='p-entrevistas'> Mis planes futuros se centran en continuar explorando y conociendo las especies únicas que habitan en diversas regiones del mundo. Mi proyecto principal es seguir viajando y compartir la magia de estos encuentros con otras personas, ya sea a través de expediciones submarinas o excursiones a lugares impresionantes en nuestro país. </p>
         <p className='p-entrevistas'> Para aquellos estudiantes de SieteFotógrafos interesados en aventurarse en el mundo submarino, los invito a que me contacten. Además de ser fotógrafa, soy instructora de buceo, y estaré encantada de acompañarlos en inmersiones en el Pacífico colombiano. También ofrezco la oportunidad de explorar los corales marinos en el Parque Nacional Natural Los Corales del Rosario y de San Bernardo, cerca de Cartagena, donde podrán capturar impresionantes imágenes de la fauna marina. Estoy comprometida a brindar experiencias inolvidables y enriquecedoras a todos aquellos que deseen sumergirse en el fascinante mundo de la fotografía de la naturaleza. </p>
         <img src={Paola5}  className="imagen-completa-entrevista" alt="Imgen no disponible"/>
         <h2 className='h2-entrevistas'> Muchas gracias Pao, personalmente me encantaría acompañarte en alguna de tus aventuras. ¿Hay algo más que te gustaría compartir con nuestros lectores sobre tu trabajo o tu experiencia en la fotografía de fauna silvestre?</h2>
         <p className='p-entrevistas'>  Para mí, la fotografía no solo es un arte, sino también una poderosa herramienta de educación y sensibilización ambiental. Ha sido un viaje de descubrimiento y aprendizaje constante, donde cada encuentro con la vida salvaje me ha dejado una profunda impresión. No puedo salir al campo sin mi cámara y mi objetivo de 300 milímetros, herramientas indispensables que me permiten capturar la esencia de los seres que habitan en los rincones más remotos de nuestro planeta. A veces, enfrento desafíos técnicos, como la necesidad de forzar la cámara a ISO 50.000 en condiciones de poca luz o la imposibilidad de alcanzar la distancia focal adecuada cuando los animales están lejos. Sin embargo, cada una de estas experiencias es una oportunidad única para conectarme con la naturaleza y sentirme parte de ella. </p>
        
    </div>
  )
}

export default EntrevistasPre13
