import React from 'react'
import "../styles/Premium.css";
import Daniel1 from "../img/Daniel1.jpg";
import Daniel2 from "../img/Daniel2.jpg";
import Daniel3 from "../img/Daniel3.jpg";
import Daniel4 from "../img/Daniel4.jpg";
import Daniel5 from "../img/Daniel5.jpg";
import Premium6 from "../img/Premium6.jpg";
import Daniel7 from "../img/Daniel7.jpg";
import Daniel8 from "../img/Daniel8.jpg";
import Daniel9 from "../img/Daniel9.jpg";
import Daniel10 from "../img/Daniel10.jpg";

const EntrevistasPre6 = () => {
  return (
    <div>
       <h1 className='h1-entrevistas'>FOTOGRAFO DANIEL MAYRIT </h1>
         <h2 className='p-entrevistas-PRINCIPAL'>"El control de la imagen es algo que siempre ha preocupado mucho al poder", Daniel Mayrit, autor de "Imágenes autorizadas"</h2>
         <div className='Contenedor-texto-entrevistas'>
         </div>
         <div className='imagen-completa-entrevista-ENTREVISTAGENERAL'>
         <div className='imagen-completa-entrevista'>
            <img src={Daniel1}  className="img-entrevistas" alt="Imgen no disponible"/>
            </div>   
         </div> 
         <p className='p-entrevistas'> Tras el éxito de su anterior trabajo, You Haven't Seen Their Faces, que le valió el premio al mejor fotolibro en el festival de fotografía Paris Photo, el fotógrafo Daniel Mayrit estrena nuevo trabajo en el que se centra en España y las consecuencias que tiene la reciente Ley Mordaza en la ciudadanía, un proyecto que actualmente se encuentra expuesto en la Galería Cero de Madrid. Hablamos con él para conocer a fondo su nuevo trabajo.</p>
         <p className='p-entrevistas'>Imágenes autorizadas es un proyecto cuya finalidad es llevar hasta sus últimas consecuencias la Ley de Seguridad Ciudadana, también conocida como Ley Mordaza. Una ley muy ambigua que simplificándola un poco, prohíbe a todo ciudadano crear o compartir imágenes en las que se reconozcan a las fuerzas del Estado. Esto no se aplica a la propia policía o cualquier órgano estatal, que son quienes si tienen potestad para la gestión de las imágenes.</p>
         <h2 className='p-entrevistas-PRINCIPAL'>En una Europa que vive cada vez más en la sociedad de la imagen, parece ser que el poder comienza a residir en quien tiene la capacidad de crear las imágenes y por ende, de dirigir el discurso visual de lo que existe. ¿Crees que esta lógica irá a más o en el caso de España es un intento de ponerle vallas al campo?</h2>
         <p className='p-entrevistas'> Fíjate que en realidad yo diría que el diagnóstico es el contrario. Sí que es verdad que el poder reside en quien controla, entre otras cosas, la producción de imágenes, pero esto ha sido así desde el principio de los tiempos. Desde los chamanes en las cuevas hasta las vidrieras en las iglesias, y de ahí a los gobiernos actuales, pasando por los medios de comunicación. El control de la imagen siempre es algo que ha preocupado mucho al poder precisamente porque tiene una influencia mucho menos obvia que otros poderes, como el militar, por ejemplo, pero esa influencia es mucho más duradera y de mucho más calado. Con la ventaja añadida de que aquellos a los que se controla normalmente no se dan (o no nos damos) cuenta de que estamos siendo controlados. Es un poder mucho más invisible, precisamente porque a la ciudadanía no se nos enseña a "leer" imágenes, sólo palabras.</p>
         <p className='p-entrevistas'> Sin embargo estamos asistiendo a un momento de cambio radical en este sentido. Pero no sólo en Europa, ni siquiera en Occidente. Esto está ocurriendo a escala casi global (salvando las brechas digital y generacional, obviamente, tanto allí como aquí). Cada vez es más fácil producir imágenes, eso es innegable. Y cuando hay más gente produciendo más imágenes, se ensancha nuestro universo de lo posible, somos más capaces de imaginarnos otras realidades, otros mundos, otras soluciones, otro tipo de representaciones y otro tipo de relatos que nos hablen del mundo en el que vivimos. Y esto es peligroso para el poder (para cualquier poder), porque su discurso unidireccional que viene de arriba a abajo ya no tiene por qué ser la única alternativa posible, y ni mucho menos la mejor.</p>
         <div className='Contenedores de imagenes'>
            <img src={Daniel2}  className='CDI' alt="Imgen no disponible"/>
            <img src={Premium6}  className='CDI' alt="Imgen no disponible"/>
            <img src={Daniel5}  className='CDI' alt="Imgen no disponible"/>
            <img src={Daniel3}  className='CDI' alt="Imgen no disponible"/>
         </div> 
         <h2 className='p-entrevistas-PRINCIPAL'>A la ciudadanía no se nos enseña a "leer" imágenes, sólo palabras.</h2>
        <p className='p-entrevistas'> Sin embargo el caso de la Ley Mordaza es diferente. No creo que estemos ante esa amplitud de miras en la que se trate de cortar el empoderamiento de la ciudadanía a través de la imagen. Eso opera a otro nivel e implica sobre todo a medios de comunicación y a muchos más agentes. El caso de la Ley Mordaza me parece más una censura de las de "toda la vida": hay algo que no nos gusta que se vea (la violencia policial), y lo tapamos con una ley. No se intenta controlar el discurso visual general, sino la representación concreta del propio Estado (ejemplificado en la policía). Sus miras son mucho más cortas y si me apuras diría que más chapuceras. De lo que peca de hecho es precisamente de no entender todo lo anterior, de no comprender cómo funciona el mundo de la imagen hoy en día. En ese sentido no es poner puertas al campo. Es poner un cartel de prohibido pisar y esperar que la gente no lo pise. Lo que intento con este proyecto es precisamente poner esto último de relieve e invitar a pisar el campo, que es también nuestro y es de todxs.</p>
        <p className='p-entrevistas'> Siglos atrás, tan solo los que eran poderosos social o económicamente, poseían imágenes, independientemente de su soporte. Ya sean pinturas de reyes o retratos fotográficos cuando la fotografía era todavía un lujo. Con el avance de la tecnología, lo que parece imposible es no encontrar imágenes de una persona en Internet, algo sobre lo que trabajaste en tu premiado trabajo You Haven't Seen Their Faces.</p>
        <p className='p-entrevistas'> Parece ser que la lógica visual se invierte y ahora ser invisible visualmente nos hace poderosos. Si no existo, parece que no se ven mis acciones y por tanto no hay culpables o responsables de ninguna acción, tan solo cosas que pasan como el viento que aparece una tarde o la salida del sol por las mañanas.</p>
        <h2 className='p-entrevistas-PRINCIPAL'> ¿Te parece que si esto va a más, vamos a llegar a un momento que una sesión en el Parlamento podría ser mirar pantallas como si estuviéramos en la bolsa, donde se anuncien las nuevas leyes o cambios legislativos por un Estado que no va más allá de una fachada visual, sin cabezas visibles? Suena un poco a película de ficción ochentera, pero viendo la evolución que está teniendo Europa tiene sentido.</h2>
        <p className='p-entrevistas'> Efectivamente esto entronca con lo que te contaba hace un momento. Esa censura previa que promueve la Ley Mordaza se dirige exactamente a invisivilizar una situación que está ocurriendo, para que parezca que no ocurre. Y en ese gesto reside una carga importante de poder. Igual que, como dices, en mi trabajo anterior buena parte del poder de las 100 personas que retrataba (banqueros, directivos, políticos...) reside también en su anonimato, en su falta de exposición pública y por ende su no necesidad de rendir cuentas ante el público, porque para éste es como si esas 100 personas no existieran.</p>
        <div className='Contenedores de imagenes'>
            <img src={Daniel7}  className='CDI' alt="Imgen no disponible"/>
            <img src={Daniel8}  className='CDI' alt="Imgen no disponible"/>
            <img src={Daniel9}  className='CDI' alt="Imgen no disponible"/>
            <img src={Daniel10}  className='CDI' alt="Imgen no disponible"/>
         </div> 
        <p className='p-entrevistas'> Sin embargo en el polo opuesto, en la exposición extrema, también existe poder. Desde el boom del fenómeno de las "celebrities" hasta la exposición política a lo Donald Trump. Un caso paradigmático me parece el de Martin Shkreli, un joven empresario que el año pasado compró la patente de un medicamento contra el VIH para acto seguido incrementar su precio en un 5000%. Pasó a ser el mayor villano de América y se le abrió un proceso judicial, pero en vez de esconderse decidió monitorizar su vida y ofrecerla en streaming abierto 24 horas al día, consiguiendo un claro objetivo: que esa exposición constante generase tal cantidad de "ruido", de material visual inútil, que al final resultase complicadísimo distinguir entre lo relevante (el juicio, sus dimensiones financieras, etc.) y la morralla. Es un gesto muy bien utilizado, desgraciadamente para unos fines muy perversos.</p>
        <p className='p-entrevistas'> Volviendo al caso que planteas del parlamento, no hace falta irse a películas de ciencia ficción, tenemos ejemplos de sobra en la realidad española. Hasta hace unos meses en la Asamblea de Madrid** no se grababan los plenos ni nada de lo que acontecía allí dentro.** Cuando los diputados y diputadas de Podemos empezaron a grabarlos con el móvil (que nada lo impedía) y a colgarlos en streaming fue cuando la Asamblea decidió regularlo y ofrecerlos a través de un canal oficial del gobierno regional. No se qué escenario me da más miedo, si el que planteas de pantallas (¿de plasma?) sin personas o la opacidad absoluta que existía hasta ahora....</p>
        <p className='p-entrevistas'> El reciente escándalo alrededor de las escuchas de Jorge Fernández Díaz pone de manifiesto muchas de las cosas de las que versa Imágenes autorizadas. El problema no es lo que haya hecho (o no) el Ministro de Interior, sino que exista un documento audiovisual que evidencia una realidad pero que no ha sido autorizado por el Estado. Parece que si no está aprobado por el Estado, la realidad que muestre una imagen o una grabación es completamente cuestionada, algo inverosímil.</p>
        <p className='p-entrevistas'> Ya que este es un tema que has trabajado a fondo, me gustaría conocer en qué situación se encuentra España respecto a otros países en este tipo de asuntos.</p>
        <p className='p-entrevistas'> Lamentablemente España, o más concretamente su gobierno, está desarrollando una estrategia de distracción que no es de ahora, viene de hace unos años. Se trata de poner constantemente en duda todo lo que no es afín a los intereses del gobierno (que no necesariamente del país). Una vez más, es la estrategia de generar ruido mediático para que al final seamos incapaces de distinguir entre lo relevante y lo que no. Apuntar al mensajero para esquivar la cuestión de fondo. Es una estrategia hábil y de hecho les está funcionando relativamente bien. En el caso que mencionas no se cuestionan las acciones del ministro, que ni se molesta en negarlas, sino en por qué esas acciones han salido a la luz, dando por hecho que lo propio hubiese sido que se quedasen en privado. Ya se consiguió apartando a Baltasar Garzón hace unos años y ocurre continuamente en otros ámbitos también, como en el caso De Gea. El objetivo es hacer campaña, con la complacencia de muchos medios de comunicación, para cuestionar, invalidar y menospreciar las pruebas (sean imágenes, grabaciones, capturas de pantalla...). Se utiliza la presunción de inocencia como escudo contra la rendición de cuentas.</p>
        <p className='p-entrevistas'> Obviamente es un tema que no sólo está presente aquí, pero parece que recoge lo peor de nuestro entorno. En esa línea el gobierno italiano ya declaró inconstitucional la Ley Alfano hace unos años, que tenía objetivos similares (aunque no idénticos) a ciertos aspectos de la Ley Mordaza. Como diferencia siempre hablo de la estrategia radicalmente opuesta que se ha adoptado respecto al mismo asunto en un país como Estados Unidos, en el que la violencia policial parece ser mucho más grave que aquí. Allí todos los coches patrullas, helicópteros e incluso agentes llevan cámaras incrustadas que graban lo que ocurre en todo momento, y no son pocos los casos en los que imágenes incriminatorias han acabado en los medios de comunicación. Nunca el foco mediático se ha puesto en las imágenes, sino en las acciones que se ven en ellas. Allí las imágenes han derivado en protestas legítimas ciudadanas. Aquí, las protestas legítimas ciudadanas han derivado en la censura de sus imágenes.</p>
       
        <p className='p-entrevistas'> Para tí es muy importante que cuando expones tu trabajo, este tenga una relación con el espectador (no se si este sería este el nombre más correcto) que vaya más allá del mero observar, reflexionar un poco y a otra cosa, sino que realmente pueda activar resortes en personas y a su vez puedan tener consecuencias a medio-largo plazo para que haya cambios en la sociedad. Algo que me atrevo a creer que es un poco lo que buscas con tus últimos proyectos.</p>
        <h2 className='p-entrevistas-PRINCIPAL'> ¿Qué estrategias intentas desarrollar para que la interacción entre tu trabajo y sus consumidores sea más intensa</h2>
        <p className='p-entrevistas'>Efectivamente, la relación entre el trabajo y público no solamente es importante sino que es vital. Creo que ha llegado la hora de asumir (si es hay alguien que no lo haya hecho ya) que el arte y la imagen en general son incapaces de cambiar el mundo desde las paredes de una galería de arte. Lo cual no quiere decir que no tengan lugar dentro de la galería. Todo suma, y el espacio expositivo también lo hace porque genera un tipo de lectura particular, y puede además generar noticias que multipliquen el alcance y difusión de la propia obra. Pero si lo que queremos es afectar al mundo en el que vivimos, no basta sólo con eso. Por eso implicar al espectador en procesos que vayan más allá de mirar y contemplar es crucial. Y esto es algo de lo que cada vez estoy más convencido, pero también es algo difícil porque, digámoslo así, no es precisamente lo que te enseñan en las escuelas de arte.</p>
     
        
    </div>
  )
}

export default EntrevistasPre6
