import React from 'react'
import TP113 from "../img/TP113.jpg"
import TP114 from "../img/TP114.jpg"
import Tu18 from "../img/Tu18.jpg"

const Premiumtutorial18 = () => {
  return (
    <div>
       <h1 className='h1-entrevistas'>¿Cómo cambiar el tamaño de las fotografías?</h1>
       <h2 className='subtitulo-entrevistas'>¿POR QUÉ ÍBAMOS A QUERER CAMBIAR EL TAMAÑO DE NUESTRAS FOTOS?</h2> 
         <p className='p-entrevistas'>Pues por muchos motivos, como siempre el principal y más importante y el que más me gusta para casi todo es: "porque nos da la gana". Es fantástica  esa respuesta, suele callar bastantes bocas indiscretas... ¿Por qué no respetas la regla de los tercios? Porque no me da la gana... ¿Por qué pasas las fotos a blanco y negro? Porque me da la gana... ¿Por qué llevas el pelo así? Porque me da la gana... ¿Por qué no sigo con el artículo? Porque se me va la pinza y no me centro... venga vale...sigo... Uno de los motivos más habituales son las exigencias de concursos y exposiciones colectivas...</p>
         <h2 className='subtitulo-entrevistas'>CONCURSOS Y EXPOSICIONES</h2> 
         <p className='p-entrevistas'>En el caso de los primeros, cuando la participación se puede realizar por internet, suelen exigir un máximo de dimensiones por tema de almacenamiento de imágenes, se necesitan que pesen poco pero que tengan suficiente calidad para poder ser visualizadas correctamente. Y si lo que piden es un mínimo suele ser por la intención de imprimirlas. Lógicamente en estos casos debemos ajustarnos al píxel, tanto si exigen un mínimo como si piden un máximo.</p>
         <p className='p-entrevistas'>En cuanto a las exposiciones colectivas suelen tener razones de estilo y calidad. Se necesita que las fotos tengan un tamaño acorde a todos los trabajos que se van a exponer y que tengan suficiente calidad para ser impresas sin problemas. Es lógico en ambos casos... lo que no tiene sentido, como ya te conté y demostré, es lo de la resolución, eso de los 300ppp o 72ppp o los pppquetedelagana si nos piden el tamaño de la foto en píxeles. Pero no tendremos más remedio que hacer lo que nos exigen si no queremos que nos descarten por esa pamplina.</p>
         <h2 className='subtitulo-entrevistas'>IMPRIMIR LAS FOTOS</h2> 
         <p className='p-entrevistas'>Otro motivo para querer cambiar las dimensiones de una fotografía es la de imprimirla nosotros mismos o a través de una imprenta. Si la quieres imprimir tú, ya sabes, ajusta el tamaño en centímetros o milimetros o metros (en kilometros no creo) y pon la resolución que creas conveniente, pero no te preocupes por la resolución si los ajustas en píxeles, ya la especificarás en la impresora. Si la mandas a que te la impriman, atiende a las indicaciones que te den, todavía hay gente en las imprentas que no saben lo de la resolución para las imágenes digitales o que sólo se manejan en centímetros y milímetros. Qué le vamos a hacer.</p>
         <h2 className='subtitulo-entrevistas'>SUBIRLAS A INTERNET</h2> 
         <p className='p-entrevistas'>Como último motivo que se me ocurre está el de subirlo a internet, incluyendo webs, foros, blogs, redes sociales, etc. En estos casos puede ser que quieras subirlas suficientemente pequeñas para que no puedan "robártelas" e imprimirlas y suficientemente grandes para que se vean bien. Así que debes tener en cuenta la resolución de los dispositivos en los que se van a ver tus fotos, en la gran mayoría de los casos pantallas de móviles, tablets y monitores de ordenador.</p>
         <img src={TP113}  className="img-entrevistas" alt="Imgen no disponible"/>
         <p className='p-entrevistas'>Teniendo en cuenta eso y que en la mayoría de las ocasiones tus fotos no se van a visualizar a pantalla completa, podrías reducirlas a 1.200px y se verían genial en casi todos los dispositivos y si alguien te las "robase"no podría imprimirlas (con calidad aceptable) más grande que 20x25cms (un poco más pequeño que un folio) y si quieres ajustar más, tengo comprobado que a 1.000px el lado mayor  se siguen viendo más que bien y no pueden imprimirse (aceptablemente) a más de 15x20cms (redondeando). Y a 800px de lado mayor el máximo para imprimir pasaría a ser de 8x12cms aproximadamente.</p>
         <img src={Tu18}  className="img-entrevistas" alt="Imgen no disponible"/>
         <h2 className='subtitulo-entrevistas'>LA MAYORÍA DE LA VECES NOS LO HACEN OTROS...</h2> 
         <p className='p-entrevistas'>Es cierto que la mayoría de las situaciones en las que se va a cambiar el tamaño de nuestras imágenes no necesitamos hacer nada. ejemplo a la hora de llevarlas a una imprenta, si indicamos el tamaño al que queremos el trabajo final, supuestamente ellos mismos se encargarían de ajustar. O si queremos subir nuestra última y molona foto a Instagram, esta misma plataforma se encarga de cambiar el tamaño (y de paso hacer algún que otro destrozo en la calidad, pero bueno, "hay que estar").</p>
         <p className='p-entrevistas'>Aún así yo creo que lo mejor es que nosotros mismos ajustemos el tamaño final, para que no nos hagan cosas raras. Especialmente en redes sociales, la compresión que hacen de la imagen para que ocupe menos es criminal... tengo que hacer un tutorial con algunos truquillos (que los hay bastante eficaces) que le podemos aplicar a nuestras fotos para minimizar daños... Bueno, a lo que iba.... que creo que es mejor que nosotros tengamos el control de nuestro trabajo en el mayor número de pasos posibles, por ello creo que este artículo puede ser útil.</p>
         <h2 className='subtitulo-entrevistas'>ALGUNAS COSAS A TENER EN CUENTA</h2> 
         <p className='p-entrevistas'>Lo primero es decirte que si, cuando termines de leer el tutorial, piensas que todo esto es muy complicado para ti (que te aseguro que no lo es) debes saber que hay programas, tanto de esos que te tienes que instalar como directamente online, cuya casi exclusiva función es la de cambiar el tamaño de la imágenes, algunos de ellos son gratuitos. Normalmente te pondría ahora varios enlaces a dichos programas, pero es que en esta ocasión no conozco ninguno. El único que tuve que usar hace ya siglos se llamaba "Image Resizer" (o algo parecido) y no sé si sigue existiendo. No te puedo hablar ni bien ni mal de él pues, como ya te he dicho, hace muchísimo tiempo que no he necesitado usarlo. Tanto Lightroom como Photoshop, como casi cualquier software procesador de imágenes es capaz de hacer los cambios de tamaño muy eficazmente, en pocos pasos y ninguno es complicado.</p>
         <h2 className='subtitulo-entrevistas'>CAMBIAR EL TAMAÑO NO ES HACER ZOOM</h2> 
         <p className='p-entrevistas'>Supongo que no hace falta que te lo diga, pero cambiar el tamaño de una imagen no es hacer zoom sobre ella pellizcando el móvil o usando la herramienta lupa. Eso solamente cambia el tamaño de visualización. Lo que vamos a aprender con este tutorial es a hacer más grande o más pequeño el archivo final de nuestra foto o, lo que es lo mismo, cambiar las dimensiones (ancho y alto), a más o a menos.</p>
         <h2 className='subtitulo-entrevistas'>TAMPOCO ES COMO RECORTAR, PERO SE CREAN Y SE DESTRUYEN PÍXELES</h2> 
         <p className='p-entrevistas'>Ya vimos en un tutorial anterior cómo podemos recortar una fotografía. Acción que implica eliminar parte de los píxeles que forman la imagen. Al redimensionar no quitamos píxeles... al menos aparentemente. Porque al hacer más grande una foto es como si ésta estuviera impresa sobre una rejilla o esas telas hechas con crochet y la estirásemos hasta que quedasen huecos vacíos, esos espacios se rellenarían con algo que se parece a lo de alrededor, dando la sensación de que siempre estuvo así.</p>
         <img src={TP114}  className="img-entrevistas" alt="Imgen no disponible"/>
    </div>
  )
}

export default Premiumtutorial18
